POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "chuck",
    "number": "1234"
}

###
PUT http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "chuck",
    "number": "1234"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "missing number"
}

###
POST http://localhost:3001/api/persons/