POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "chuck",
    "number": "123"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "missing number"
}

###
POST http://localhost:3001/api/persons/